version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: yarn install
  lint:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: yarn install
      - run:
          name: ESLint
          command: yarn eslint
  test:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: yarn install
      - run:
          name: "Run jest"
          command: yarn jest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
